title: Standard Public Code Jekyll Theme
permalinks: pretty

include:
  - CONTRIBUTING.md
  - AUTHORS.md
  - LICENSE.md
  - CONTRIBUTORS.md

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-avatar
  - jemoji
  - jekyll-mentions

# Exclude the `vendor` folder created by build process
exclude:
  - vendor

# To replace the standard GitHub metadata if it fails: https://help.github.com/articles/repository-metadata-on-github-pages/
license:
  key: eupl
  name: European Union Public License 1.2
  spdx_id: EUPL-1.2

# Add a custom copyright message
# copyright: Standard for Public Code

# Enable Table of Contents displaying
toc: true

# Show the navigation
# show_navigation: true

# Show breadcrumbs on every page
show_breadcrumbs: true

# Hide the Foundation footer
# hide_foundation_footer: true

defaults:
  -
    scope:
      path: "index.md"
    values:
      order: 0 # Show the index at the top of the navigation
  -
    scope:
      path: "LICENSE.md"
    values:
      order: 100 # Show the license at the bottom of the navigation

titles_from_headings:
  strip_title: true
